[package]
name = "config-error-repro"
version = "0.1.0"
authors = ["Manish Bellani <mbellani@github.com>"]
edition = "2018"

[dependencies]
config = { version = "0.10", features = ["toml"] }
serde = { version = "1.0", features = ["derive"] }
